name: API tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Клонирование тестового сервера
        run: git clone https://github.com/Nikita-Filonov/qa-automation-engineer-api-course.git

      - name: Установка зависимостей тестового сервера
        run: pip install -r qa-automation-engineer-api-course/requirements.txt

      - name: Запуск тестового сервера
        env:
          APP_HOST: "http://localhost:8000"
          DATABASE_URL: "sqlite+aiosqlite:///./local.db"
          JWT_ALGORITHM: "HS256"
          JWT_SECRET_KEY: "qa-automation-engineer-api-course-secret-key"
          JWT_ACCESS_TOKEN_EXPIRE: 1800
          JWT_REFRESH_TOKEN_EXPIRE: 5184000
        run: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ./qa-automation-engineer-api-course &

      - name: Установка зависимостей тестов
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск API тестов и генерация отчета Allure
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses=2

      - name: Сохранение отчёта Allure как артефакта
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  publish_report:
    if: always()
    needs: [run_tests]
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Загрузка результатов Allure
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Генерация Allure отчета с историей
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Деплой отчета на страницу
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
